Create validation file & define validation function
nourish-team/nourish-backend pull request #72
Opened 2023-11-01 10:18 UTC by oddpharmacy

Write a basic reusable function to validate strings for malicious characters.

feat: implement username validation

Validate username strings for malicious characters and add basic error handling.

Note: To improve error handling in future updates.

fix: remove unnecessary escape characters

chore: remove linting errors

# Description

Add short description about what you did and why.

# Closes issue(s)

Resolves #[issue number here]

# How to test

# Changes include

1. add
2. changes
3. here

# Checklist

- [ ] I have tested this code
- [ ] I have updated the README

2023-11-01 12:43 UTC, FefesG5 requested changes
Hi Lisa looks good,

Wondering if you can add ' ; ' into the const malicious pattern. Seems many SQL injections have this symbol ' ; ' inside the injection string.  (semi colon)

2023-11-01 13:15 UTC, Anissa3005 requested changes
Great job. 
The only change (besides from Chai's request) is to make the error message less explicit.

2023-11-01 13:15 UTC, Anissa3005 commented on src/service/signup.service.ts
> +        'Invalid input. Please check your input for malicious characters.',
This is to explicit to send back to the user. "Please check your inputs" is enough. To explicit error messages (send to the user) can be dangerous.

2023-11-04 02:41 UTC, FefesG5 approved these changes
All good. Semicolon added.

2023-11-07 01:07 UTC, Anissa3005 approved these changes
LGTM 🚀

2023-11-07 01:15 UTC, shonancanuck approved these changes
Looks good to me

2023-11-07 01:52 UTC, merged