doc: updating the README
nourish-team/nourish-backend pull request #79
Opened 2023-11-15 07:34 UTC by Anissa3005

Previously, our README file was cluttered with unnecessary information. I have cleaned up the README and update it with new information

# Description

Add short description about what you did and why.

# Closes issue(s)

Resolves #[issue number here]

# How to test

# Changes include

1. add
2. changes
3. here

# Checklist

- [ ] I have tested this code
- [ ] I have updated the README

2023-11-15 23:33 UTC, oddpharmacy approved these changes
Lgtm :)

2023-11-16 06:07 UTC, FefesG5 approved these changes
Looks good to me. I had to check the preview to see what is kept in the readme. The github comparison is difficult to see.

2023-11-16 07:18 UTC, shonancanuck commented on README.md
> +To keep in simple we use Docker to run an image of PostgreSQL database.
Super minor grammar/spelling:
To keep *in* simple
suggested: it, things

2023-11-16 07:21 UTC, shonancanuck commented on README.md
> +DATABASE_URL=postgresql://dbuser:passworddb@localhost:5432/namedb
This is the url for a local instance. We can probably provide the url for the docker instance?

2023-11-16 07:26 UTC, shonancanuck requested changes
Looks good! Two small requests.

2023-11-17 07:10 UTC, shonancanuck approved these changes

2023-11-17 07:11 UTC, merged