Create additional validation checks for use in user creation
nourish-team/nourish-backend pull request #80
Opened 2023-11-19 04:38 UTC by oddpharmacy

# Description

Implement additional checks which cover common scenarios to improve the overall security of the user creation process. This includes length and empty character checks for the uid, username and email user inputs.

# Closes issue(s)

Resolves #74 

# Changes include

1. isNotEmptyInput, isValidUID, isValidEmail, and isValidUsername functions.

# Checklist

- [ ] I have tested this code
- [ ] I have updated the README

2023-11-20 07:41 UTC, shonancanuck reviewed
Everything looks great to me. I made one comment, but it's more an observation than a suggestion.

2023-11-20 07:41 UTC, shonancanuck commented on src/utils/validation.ts
> +  isValidUID(input: string): boolean {
Depending on the particular pattern for UID we're using, this could potentially be a little more stringent, but I'm not even sure that's necessary.

2023-11-21 09:35 UTC, Anissa3005 requested changes
Great Job!

when I run Eslint i saw some errors can you please fixed them and commit them before merging. Some errors are from an other PR but Chai and Me fixed them so maybe wait on his PR to be merged so you can rebase.

2023-11-21 09:35 UTC, Anissa3005 commented on src/service/signup.service.ts
> +        throw new Error('User with this username or email already exists.');
I think there is a better to handle the errors but this should be done in an other issue.  It's okay for now but maybe create a To Do in your PR comment and add it there

2023-11-21 11:43 UTC, oddpharmacy commented
Commits messed up. New branch and subsequent PR to replace.

2023-11-21 11:43 UTC, closed without merging