Create additional validation checks for use in user creation
nourish-team/nourish-backend pull request #82
Opened 2023-11-21 11:42 UTC by oddpharmacy

# Description

Implement additional checks which cover common scenarios to improve the overall security of the user creation process. This includes length and empty character checks for the uid, username and email user inputs.

Note: The previous PR and branch had some commit issues so I have created a new branch.

# Closes issue(s)

Resolves #74 

# How to test?

### Test using Postman

- Start the server in your local environment. -> `npm run dev`
- Ensure that you have run the necessary prisma scripts, created a local database, and have linked the database url in your env file.
- Open Postman and make a POST req to the _signup_ route. -> `http://localhost:8080/signup`

**_Case 1: A successful request and creation of a new user_**
- Paste the following content as the body to your POST request:
`{
  "username": "totoroo",
  "email": "totoroo@example.com",
  "uid": "aBcDeF1234567890aBcDeF1234--"
}
`
- You should receive an 'id' and 'username' back as a response.

_**Case 2: Invalid inputs entered / Duplicate users**_
- Paste the following content as the body to your POST request:
`{
  "username": "totoroo",
  "email": "totoroo@example.com",
  "uid": "a"
}
`
- You should receive the following error as a response: `Error: Something went wrong. Please check your inputs.`
- Different error messages will pop up depending on the user's inputs. 

# Errors
If you encounter a Typescript error when trying to run the server, make the fix below in _login.service.ts_ on line 14:
`    return loginModel.updateAccessTokenLogin(userId);
`

# Changes include

1. isNotEmptyInput, isValidUID, isValidEmail, and isValidUsername functions.

# Checklist

- [x] I have tested this code

2023-11-22 03:04 UTC, shonancanuck commented on src/controller/signup.controller.ts
> +        res.status(400).send(message.toString());
Should we be sending an explicit error message to the frontend here? Maybe a generic message is better in this case.

2023-11-22 09:00 UTC, shonancanuck commented on src/controller/signup.controller.ts
> +        res.status(400).send(message.toString());
I see that most of our errors here are just strings, but we should be careful what we are sending back to the client. Maybe in this case we log the error in the backend and send a generic message to the front?

2023-11-22 09:05 UTC, shonancanuck commented on src/service/signup.service.ts
> +  target?: string;
Prisma errors sometimes also contain the `errorCode` property (which is different from `code` for some confusing reason). It's probably good to include this too.

2023-11-22 09:17 UTC, shonancanuck requested changes
Nice job. I like how you created the CustomError class. It was kind of awkward that the Prisma errors were all separate classes. Just two small points. We can wait to see how the others feel about the response message from the controller if you want.

2023-11-27 14:22 UTC, oddpharmacy commented
CLOSED> NEW PR MADE

2023-11-27 14:22 UTC, closed without merging